# -*- coding: utf-8 -*-
"""vector_math.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LFBNlQY4PrjzlyG7eo5BWvMCyxxUs-aV
"""

# vector_math.py

class Vector:
    """
    Класс для работы с N-мерными математическими векторами.

    Поддерживает сложение векторов, умножение на скаляр, скалярное произведение
    и вычисление длины вектора (нормы).
    """

    def __init__(self, *args: float) -> None:
        """
        Инициализация вектора с произвольным количеством координат.

        Аргументы:
            *args: Произвольное количество чисел (координат вектора)

        Примеры:
            v1 = Vector(1, 2, 3)      # 3-мерный вектор
            v2 = Vector(4, 5)         # 2-мерный вектор
            v3 = Vector(1.5, 2.7, 3.1)  # Вектор с дробными числами
        """
        self._coords = tuple(args)  # Используем кортеж для неизменяемости координат

    def __str__(self) -> str:
        """
        Строковое представление вектора для пользователя.

        Возвращает:
            str: Строка вида "Vector(1, 2, 3)"
        """
        # Форматируем координаты с помощью repr() для корректного отображения
        coords_str = ', '.join(repr(coord) for coord in self._coords)
        return f"Vector({coords_str})"

    def __repr__(self) -> str:
        """
        Строковое представление вектора для разработчика (совпадает с __str__).

        Возвращает:
            str: Строка вида "Vector(1, 2, 3)"
        """
        return self.__str__()

    def __add__(self, other: 'Vector') -> 'Vector':
        """
        Сложение векторов.

        Аргументы:
            other: Другой вектор для сложения

        Возвращает:
            Vector: Новый вектор с покомпонентной суммой координат

        Исключения:
            ValueError: Если размерности векторов не совпадают
        """
        if not isinstance(other, Vector):
            raise TypeError(f"Сложение возможно только с вектором, получен {type(other).__name__}")

        if len(self._coords) != len(other._coords):
            raise ValueError(f"Векторы разной размерности: {len(self._coords)} != {len(other._coords)}")

        # Покомпонентное сложение
        new_coords = [a + b for a, b in zip(self._coords, other._coords)]
        return Vector(*new_coords)

    def __mul__(self, other: 'Vector | int | float') -> 'Vector | float':
        """
        Умное умножение:
        - Если other - число → скалярное умножение (вектор * число)
        - Если other - вектор → скалярное произведение (вектор * вектор)

        Аргументы:
            other: Число (int/float) или другой вектор

        Возвращает:
            Vector: Если умножали на число (новый вектор с умноженными координатами)
            float: Если умножали на вектор (скалярное произведение)

        Исключения:
            TypeError: Если other не является числом или вектором
            ValueError: Если размерности векторов не совпадают
        """
        # Случай 1: Умножение на число (скалярное умножение)
        if isinstance(other, (int, float)):
            new_coords = [coord * other for coord in self._coords]
            return Vector(*new_coords)

        # Случай 2: Умножение на вектор (скалярное произведение)
        elif isinstance(other, Vector):
            if len(self._coords) != len(other._coords):
                raise ValueError(f"Векторы разной размерности: {len(self._coords)} != {len(other._coords)}")

            # Скалярное произведение: сумма произведений соответствующих координат
            dot_product = sum(a * b for a, b in zip(self._coords, other._coords))
            return dot_product

        # Случай 3: Неподдерживаемый тип
        else:
            raise TypeError(f"Умножение возможно только на число или вектор, получен {type(other).__name__}")

    def __rmul__(self, other: 'Vector | int | float') -> 'Vector | float':
        """
        Правое умножение (число * вектор).
        Нужен для поддержки операций вида: 10 * Vector(1, 2, 3)
        Аргументы:
            other: Число (int/float) или другой вектор
        Возвращает:
            Результат умножения (аналогичен __mul__)
        """
        # Левое и правое умножение симметричны для скалярного умножения
        return self.__mul__(other)

    def __len__(self) -> int:
        """
        Возвращает размерность вектора (количество координат).
        Возвращает:
            int: Количество координат вектора
        """
        return len(self._coords)

    def __getitem__(self, index: int) -> float:
        """
        Позволяет обращаться к координатам вектора через индексы.
        Аргументы:
            index: Индекс координаты (начиная с 0)
        Возвращает:
            float: Значение координаты
        Пример:
            v = Vector(1, 2, 3)
            print(v[0])  # 1
            print(v[1])  # 2
        """
        return self._coords[index]

    @property
    def norm(self) -> float:
        """
        Вычисляет евклидову норму (длину) вектора.
        Возвращает:
            float: Длина вектора
        Пример:
            v = Vector(3, 4)
            print(v.norm)  # 5.0
        """
        # Суммируем квадраты координат и извлекаем квадратный корень
        return sum(coord ** 2 for coord in self._coords) ** 0.5

    @property
    def coords(self) -> tuple:
        """
        Возвращает кортеж координат вектора (только для чтения).
        Возвращает:
            tuple: Кортеж с координатами вектора
        Примечание:
            Возвращается копия, чтобы предотвратить изменение исходных данных.
        """
        return self._coords

    def __eq__(self, other: object) -> bool:
        """
        Сравнивает два вектора на равенство.
        Аргументы:
            other: Другой объект для сравнения
        Возвращает:
            bool: True если оба вектора имеют одинаковые координаты
        """
        if not isinstance(other, Vector):
            return NotImplemented

        return self._coords == other._coords

    def __hash__(self) -> int:
        """
        Позволяет использовать векторы в качестве ключей словаря.
        Возвращает:
            int: Хэш-значение вектора
        """
        return hash(self._coords)


def main() -> None:
    """
    Демонстрация работы класса Vector.
    """
    print("Демонстрация работы класса Vector")

    # Создание векторов
    v1 = Vector(1, 2, 3)
    v2 = Vector(4, 5, 6)
    v3 = Vector(3, 4)

    print(f"Созданы векторы:")
    print(f"  v1 = {v1}")
    print(f"  v2 = {v2}")
    print(f"  v3 = {v3}")
    print()

    # Проверка сложения
    print("Сложение векторов:")
    v_sum = v1 + v2
    print(f"  v1 + v2 = {v_sum}")
    print(f"  Ожидалось: Vector(5, 7, 9)")
    print()

    # Проверка умножения на число
    print("Умножение на число (скалярное умножение):")
    v_mul_num = v1 * 10
    print(f"  v1 * 10 = {v_mul_num}")
    print(f"  Ожидалось: Vector(10, 20, 30)")

    v_mul_num_right = 10 * v1
    print(f"  10 * v1 = {v_mul_num_right}")
    print(f"  Ожидалось: Vector(10, 20, 30)")
    print()

    # Проверка скалярного произведения
    print("Скалярное произведение векторов:")
    dot_product = v1 * v2
    print(f"  v1 * v2 = {dot_product}")
    print(f"  Ожидалось: 32 (1*4 + 2*5 + 3*6 = 4 + 10 + 18 = 32)")
    print()

    # Проверка вычисления нормы
    print("Длина (норма) вектора:")
    print(f"  ||v3|| = {v3.norm}")
    print(f"  Ожидалось: 5.0)")
    print()

    # Проверка размерности
    print("Размерность векторов:")
    print(f"  len(v1) = {len(v1)}")
    print(f"  len(v2) = {len(v2)}")
    print(f"  len(v3) = {len(v3)}")
    print()

    # Проверка доступа по индексу
    print("Доступ к координатам по индексу:")
    print(f"  v1[0] = {v1[0]}")
    print(f"  v1[1] = {v1[1]}")
    print(f"  v1[2] = {v1[2]}")
    print()

    # Проверка сравнения
    print("Сравнение векторов:")
    v4 = Vector(1, 2, 3)
    print(f"  v1 == v4 - {v1 == v4} (True, так как одинаковые координаты)")
    print(f"  v1 == v2 - {v1 == v2} (False)")
    print()

    # Обработка ошибок
    print("Обработка ошибок:")
    try:
        # Попытка сложить векторы разной размерности
        result = v1 + v3
    except ValueError as e:
        print(f"  Ошибка при сложении v1 + v3: {e}")

    try:
        # Попытка умножить на неподдерживаемый тип
        result = v1 * "строка"
    except TypeError as e:
        print(f"  Ошибка при умножении на строку: {e}")

    print()

    # Дополнительные примеры
    print("Дополнительные примеры:")
    v5 = Vector(1.5, 2.5, 3.5)
    v6 = Vector(0.5, 1.5, 2.5)
    print(f"  v5 = {v5}")
    print(f"  v6 = {v6}")
    print(f"  v5 + v6 = {v5 + v6}")
    print(f"  v5 * 2 = {v5 * 2}")
    print(f"  v5 * v6 = {v5 * v6}")
    print(f"  ||v5|| = {v5.norm:.2f}")
if __name__ == "__main__":
    main()